### ISSUE TITLE
Mapa mental

### ISSUE THREAD

**Issue by JazminloRI** [SistemasTecTlaxiaco/mapa-mental-web-3-JazminloRI#1]
[Mapa mental.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-JazminloRI/files/8446603/Mapa.mental.pdf)

**Comment by Nayee123** [comment]
20% buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado, falta mejorar el diseño
